routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('my-staffs');
});

Route::get('my-staffs', 'StaffController@myStaffs');
Route::post('bulk_delete', 'StaffController@bulkDelete');
Route::post('staff_edit', 'StaffController@editStaff');
Route::post('staff_update', 'StaffController@updateStaff');
Route::resource('staffs','StaffController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
     public function staff()
    {
        return $this->hasMany(Staff::class);
    }
}

app/Hobby.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hobby extends Model
{
    //
    public function staff()
    {
        return $this->hasMany(Staff::class);
    }
}

app/Staff.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    //
     protected $fillable = [
        'staff_name', 'contact_number','profile_pic','category_id'
    ];

    public function hobbies()
    {
        return $this->hasMany(StaffHobbyRel::class);
    }

     public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

app/StaffHobbyRel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StaffHobbyRel extends Model
{
    //
     public function staffHobby()
    {
        return $this->belongsTo(Staff::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Staff;
use App\Hobby;
use App\StaffHobbyRel;
use App\Category;

class StaffController extends Controller
{
    //

     public function myStaffs()
    {
        return view('my-staffs');
       
    }

    public function index()
    {

        $staffs = Staff::with('category')->get();
        $categories = Category::all();
        $hobbies = Hobby::all();

        $main_res=array();
        $main_res['staffs']=$staffs;
        $main_res['categories']=$categories;
        $main_res['hobbies']=$hobbies;
        return response()->json($main_res);

    }
    public function bulkDelete(Request $request)
    {
        $staffs=json_decode($request->data,true);
        
        for($i=0; $i<count($staffs); $i++){
            Staff::find($staffs[$i])->delete();
        }

        return response()->json('Success');
    }

     public function store(Request $request)
    {	
    	$image = $request->file('profile_pic');
    	$filename = time().'.'.$image->getClientOriginalExtension();
    	$destinationPath = public_path('/images');
    	$image->move($destinationPath, $filename);

        $staff = new Staff;
		$staff->staff_name = $request->staff_name;
		$staff->contact_number = $request->contact_number;
		$staff->profile_pic = $filename;
		$staff->category_id = $request->category_id;
		$staff->save();

		$staff_id = $staff->id;

		$hobbies=$request->hobby;
		for($i=0; $i<count($hobbies); $i++){
			$hobby = new StaffHobbyRel;
			$hobby->staff_id=$staff_id;
			$hobby->hobby_id=$hobbies[$i];
			$hobby->save();
		}
	
        return response()->json($staff);

    }

    public function editStaff(Request $request)
    {

       $staff = Staff::with('hobbies')->where('id',$request->id)->first();
       $categories = Category::all();
       $hobbies = Hobby::all();

       $staff_hobby = array_column(json_decode($staff->hobbies,true), 'hobby_id');
        
       $main_arr=array();
       $main_arr['staff']=$staff;
       $main_arr['categories']=$categories;
       $main_arr['hobbies']=$hobbies;
       $main_arr['staff_hobby']=$staff_hobby;
        return response()->json($main_arr);
    }

     public function updateStaff(Request $request)
    {
        
        $image = $request->file('profile_pic');
        if($image){
            $filename = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $filename);
            $staff = Staff::find($request->staff_id)->update(['profile_pic' => $filename]);
        }
       
        $staff = Staff::find($request->staff_id)->update(['staff_name' =>$request->staff_name,'contact_number' =>$request->contact_number,'category_id' =>$request->category_id]);

        $del_rec=StaffHobbyRel::where('staff_id',$request->staff_id)->delete();

        $hobbies=$request->hobby;
        for($i=0; $i<count($hobbies); $i++){
            $hobby = new StaffHobbyRel;
            $hobby->staff_id=$request->staff_id;
            $hobby->hobby_id=$hobbies[$i];
            $hobby->save();
        }

        return response()->json($staff);
    }

     public function destroy($id)
    {
        Staff::find($id)->delete();
        return response()->json(['done']);
    }


}

resources/views/create.blade.php
<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog" role="document">

    <div class="modal-content">

      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <h4 class="modal-title" id="myModalLabel">Create Staff</h4>

      </div>

      <div class="modal-body">



      		<form data-toggle="validator" action="{{ route('staffs.store') }}" method="POST">

      		<div class="form-group">

  					<label class="control-label" for="title">Staff Name:</label>

  					<input type="text" name="staff_name" class="form-control" data-error="Please enter name." required />

  					<div class="help-block with-errors"></div>

  				</div>
          <div class="form-group">

            <label class="control-label" for="title">Contact Number:</label>

            <input type="text" name="contact_number" class="form-control" data-error="Please enter number." required />

            <div class="help-block with-errors"></div>

          </div>

				<!-- <div class="form-group">

					<label class="control-label" for="title">Description:</label>

					<textarea name="details" class="form-control" data-error="Please enter details." required></textarea>

					<div class="help-block with-errors"></div>

				</div> -->

				<div class="form-group">

					<button type="submit" class="btn crud-submit btn-success">Submit</button>

				</div>

      		</form>

      </div>

    </div>

  </div>

</div>

resources/views/edit.blade.php
<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog" role="document">

    <div class="modal-content">

      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <h4 class="modal-title" id="myModalLabel">Edit Item</h4>

      </div>

      <div class="modal-body">



      		<form data-toggle="validator" action="/item-ajax/14" method="put">

      			<div class="form-group">

					<label class="control-label" for="title">Title:</label>

					<input type="text" name="title" class="form-control" data-error="Please enter title." required />

					<div class="help-block with-errors"></div>

				</div>

				<div class="form-group">

					<label class="control-label" for="title">Description:</label>

					<textarea name="details" class="form-control" data-error="Please enter details." required></textarea>

					<div class="help-block with-errors"></div>

				</div>

				<div class="form-group">

					<button type="submit" class="btn btn-success crud-submit-edit">Submit</button>

				</div>

      		</form>



      </div>

    </div>

  </div>

</div>

resources/views/my-staffs.blade.php
<!DOCTYPE html>

<html>

<head>
	<title>Anand's Practical</title>
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
</head>

<body>

	<div class="container">
			<div class="staff_record">
				<div class="row">
				    <div class="col-lg-12 margin-tb">					
				        <div class="pull-left">
				            <h2>Anand's Practical</h2>
				        </div>
				        <div class="pull-right">
							<input type="button" class="btn btn-success create_item" value="Add New"/>
							<input type="button" class="btn btn-danger bulk_delete" value="Bulk delete"/>
				        </div>
				    </div>
				</div>

				<table class="table table-bordered">
					<thead>
					   <tr>
					    <th>Srno</th>
					    <th>Select</th>
						<th>Name</th>
						<th>Contact No</th>
						<th>Category</th>
						<th>Profile Pic</th>
						<th width="200px">Action</th>
					   </tr>
					</thead>
					<tbody>
					</tbody>

				</table>
				</div>

		<div class="staff_create" style="display:none">
		</div>
	</div>

	<script type="text/javascript">

		var url = "<?php echo route('staffs.index')?>";
		var create_url = "<?php echo route('staffs.store')?>";

	</script>
	<script src="/js/staffs-ajax.js"></script> 

</body>

</html>